### ISSUE TITLE
Can you provide the data that you use?

### ISSUE THREAD

**Issue by JikoUnderscore** [marczeugs/MarkovBaj#3]
In previous version you committed a `data.json` file. 

Can you upload it somewhere, I would like to use in my projects.

**Comment by marczeugs** [comment]
I can but the problem is that it is regularly updated, so it doesn't actually make a lot of sense to commit it.

You can generate it yourself by executing this file: https://github.com/marczeugs/MarkovBaj/blob/main/src/jvmScriptsMain/kotlin/GenerateDataSet.kt

Here is the version I am currently using in case that is enough for you: [data.json.zip](https://github.com/marczeugs/MarkovBaj/files/10823372/data.json.zip)

**Comment by JikoUnderscore** [comment]
Thank you for the information.
I will run the script and increase the MB, but damn it run slow. In the mean time I will use the data you provided.

**Comment by marczeugs** [comment]
It is fairly slow yes but unfortunately there is no way to speed it up. The PushShift API rate limit is 60 requests per minute and the code already only waits one 1 second between requests. The actual Reddit API is even slower than this so I don't think there is a faster way to get the data.
